site_name: TechScapes
site_url: https://sitename.example
site_description: >
  A collection of technical documentation and guides for various technologies.
site_author: David Oshiro-Furry

theme:
  name: material
  icon:
    Admonition:
      note: null
  font: 
    text: Merriweather Sans
    code: Red Hat Mono
  logo: assets/InfiniteDreamscapes.jpg
  favicon: assets/wolfe.webp
  features:
    - navigation.footer
  palette:
    # Dark mode
    - scheme: slate
      toggle:
        icon: material/weather-sunny
      primary: green
      accent: deep purple

    # Light Mode
    - scheme: default
      toggle:
        icon: material/weather-night
        name: Light mode
      primary: black
      accent: green


markdown_extensions:
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
  - admonition
  - pymdownx.details

extra:
  generator: false
  social:
    - icon: fontawesome/brands/linkedin
      link: https://linkedin.com/in/david-oshiro-furry

nav:
  - Home: index.md
  - Networking:
      - VXLAN-EVPN:
        - Overview: Networking/VXLAN-EVPN/Overview.md
        - VXLAN: Networking/VXLAN-EVPN/VXLAN.md
        - EVPN: Networking/VXLAN-EVPN/EVPN.md
        - Design: Networking/VXLAN-EVPN/recommended-designs.md
        - Configuration:
          - Arista: Networking/VXLAN-EVPN/configuration/Arista.md
          - Cisco: Networking/VXLAN-EVPN/configuration/cisco.md
          - Juniper: Networking/VXLAN-EVPN/configuration/juniper.md
      - BGP:
        - Overview: Networking/BGP/bgp.md
      - OSPF: 
        - Overview: Networking/OSPF/ospf.md
  - Mkdocs Examples:
      - Admonitions: Mkdocs-Examples/admonitions.md
      - Diagrams: Mkdocs-Examples/diagram.md
      - Content-Tabs: Mkdocs-Examples/content-tabs.md



